version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  create-the-network-infra:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - when:
          condition:
            equal: [chore/init-stack, << pipeline.git.branch >>]
          steps:
            - run:
                name: Create the network stack
                command: |
                  chmod +x create-stack.sh
                  ./create-stack.sh monkinfra-${CIRCLE_WORKFLOW_ID} ./infra-network/network-infra.yml ./infra-network/network-infra-params.json
      - run:
          name: Update the network stack
          command: |
            chmod +x update-stack.sh
            ./update-stack.sh monkinfra-${CIRCLE_WORKFLOW_ID} ./infra-network/network-infra.yml ./infra-network/network-infra-params.json
      

workflows:
  aws-cli:
    jobs:
      - create-the-network-infra
