
Description: Provinsions an ec2 instances in the private subnets of the network

Parameters: 
  EnvironmentName:
    Description: The name of the environment. Same as the one set up for the networking infra
    Type: String

Resources: 
  ServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH on port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0    
  JumboBox:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
        - !Ref ServerSecurityGroup
      KeyName: cicd-pipeline
      ImageId: ami-00874d747dde814fa
      InstanceType: t2.micro
      Tags:
        - Key: Pipeline
          Value: !Sub ${EnvironmentName}
